base/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView
from accounts import views
from base.views import (
    principal,
    logout_user,
    usuario_vista,
    compra_vista,
    inventario_vista,
    venta_vista,
    producto_vista,
)

urlpatterns = [

    path('admin/', admin.site.urls),
    path("inicio/", principal, name="index"),
    path('', auth_views.LoginView.as_view(), name='inicio'),
    path('reiniciar/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reiniciar/enviar', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reiniciar/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reiniciar/completo', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('logout/', logout_user, name="logout"),

    path('usuarios/', include('usuario.urls')),
    path('compras/', include('compra.urls')),
    path('inventarios/', include('inventario.urls')),
    path('ventas/', include('venta.urls')),
    path('productos/', include('productos.urls')),
    # vistas de modulos
    path('Usuarios/', usuario_vista, name="usuario"),
    path('Compras/', compra_vista, name="compras"),
    path('Inventarios/', inventario_vista, name="inventario"),
    path('Ventas/', venta_vista, name="venta"),
    path('Productos/', producto_vista, name="producto"),
    path('inicio/abrir-pdf/', TemplateView.as_view(template_name='partials/archivo_pdf.html'), name='abrir_pdf'),

    path('templates/partials/', include('accounts.urls')),
    path('Registro Usuario', views.register, name='Registrarse'),
    path('cerrar-sesion/', views.cerrar_sesion, name='cerrar_sesion'),

]

usuario/models.py
from django.contrib.auth.models import User, Group
from django.core.validators import integer_validator, MaxLengthValidator, RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from safedelete.models import SafeDeleteModel


# Módulo de usuarios
# Create your models here.
# Modelo Persona
# def letras_uniquemente(value):
#     if not value.isalpha():
#         raise ValidationError("El campo solo permite letras.")
class Persona(SafeDeleteModel):
    class TipoDocumento(models.TextChoices):
        CC = 'CC ', _("Cédula de Ciudadanía")
        TI = 'TI', _("Tarjeta de Identidad")
        CE = 'CE', _("Cédula de Extranjería")

    tipo_documento = models.CharField(max_length=3, choices=TipoDocumento.choices, default=TipoDocumento.CC,
                                      verbose_name="Tipo de Documento")
    numero_documento = models.CharField(max_length=10, validators=[integer_validator, RegexValidator(r'^\d+$',
                                                                                                     message="Este campo solo permite valores numericos")],
                                        verbose_name="Número de Documento", unique=True)
    nombres = models.CharField(max_length=30, verbose_name="Nombres")
    apellidos = models.CharField(max_length=30, verbose_name="Apellidos")
    telefono = models.CharField(max_length=10,
                                validators=[integer_validator, MaxLengthValidator(10), RegexValidator(r'^\d+$')],
                                verbose_name="Número Telefónico", unique=True)
    correo_electronico = models.EmailField(max_length=50, verbose_name="Correo Electrónico", unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usuarios', null=True, blank=True)
    rol = models.ForeignKey(Group, verbose_name="Rol", on_delete=models.SET_NULL, null=True, blank=True,
                            help_text="Roles:Administrador,Vendedor,")

    class Estado(models.TextChoices):
        ACTIVO = '1', _("Activo")
        INACTICO = '0', _("Inactivo")

    estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")
    ips = models.CharField(max_length=10, verbose_name="IPS", blank=True, null=True)

    def __str__(self):
        return "%s %s %s %s %s %s" % (
            "Numero De Documento:", self.numero_documento, self.nombres, self.apellidos, ",Rol:", self.rol)

    class meta:
        verbose_name_plural = "Persona"


# Modelo de Comisión
class Comision(models.Model):
    fecha = models.DateField(auto_now_add=True, verbose_name="Fecha")
    valor_comision = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="Valor de Comisión")

    @classmethod
    def get_or_create_total_comision(cls):
        total_comision, created = cls.objects.get_or_create(pk=1)
        return total_comision

    @classmethod
    def accumulate_comision(cls, comision_valor):
        total_comision = cls.get_or_create_total_comision()
        total_comision.valor_comision += comision_valor
        total_comision.save()

    def valor_comision_formato_colombiano(self):
        return '${:,.0f}'.format(self.valor_comision).replace(',', '.')

venta/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from safedelete.models import SafeDeleteModel

from productos.models import Producto
from usuario.models import Persona, Comision


# Módulo de venta
# Create your models here.
# Modelo de Venta

class Venta(SafeDeleteModel):
    fecha = models.DateTimeField(verbose_name="Fecha", default=timezone.now)

    class Estado(models.TextChoices):
        ACTIVO = '1', _("Activo")
        INACTICO = '0', _("Inactivo")

    estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")
    persona_vendedor = models.ForeignKey(Persona, verbose_name=_("Vendedor"), on_delete=models.CASCADE,
                                         related_name="ventas_vendedor")
    persona_cliente = models.ForeignKey(Persona, verbose_name=_("Cliente"), on_delete=models.CASCADE,
                                        related_name="ventas_cliente")

    def __str__(self):
        return "%s %s" % (self.persona_vendedor, self.persona_cliente)

    class meta:
        verbose_name_plural = "Venta"


# Modelo de Detalle Venta
from django.db import models


class Detalle_Venta(models.Model):
    cantidad_total = models.PositiveIntegerField(verbose_name="Cantidad Total", default=0)
    producto = models.ForeignKey(Producto, verbose_name=_("Producto"), on_delete=models.CASCADE,
                                 related_name="detalles_venta_producto")
    venta = models.ForeignKey(Venta, verbose_name=_("Venta"), on_delete=models.CASCADE, related_name="detalles_venta")
    valor_total = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="Valor Total",
                                      editable=False)

    class Estado(models.TextChoices):
        ACTIVO = '1', _("Activo")
        INACTIVO = '0', _("Inactivo")

    estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")

    def precio_unitario(self):
        return self.producto.precio_unitario

    def precio_unitario_formato_colombiano(self):
        return '${:,.0f}'.format(self.precio_unitario()).replace(',', '.')

    def valor_total_formato_colombiano(self):
        return '${:,.0f}'.format(self.valor_total).replace(',', '.')

    def __str__(self):
        return "%s %s %s" % (self.cantidad_total, self.precio_unitario(), self.venta)

    def save(self, *args, **kwargs):
        self.valor_total = self.precio_unitario() * self.cantidad_total

        super(Detalle_Venta, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Detalles Venta"

base/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from compra.models import Compra,Detalle_Compra
from venta.models import Venta,Detalle_Venta
from inventario.models import Materia_Prima,Fabricacion
from productos.models import Producto
from usuario.models import Persona,Comision
@login_required
def principal(request):
    titulo="Bienvenido"
    compras= Compra.objects.all().count
    detalle_compras=Detalle_Compra.objects.all().count()
    ventas=Venta.objects.all().count()
    detalle_ventas=Detalle_Venta.objects.all().count()
    materias_primas=Materia_Prima.objects.all().count()
    productos=Producto.objects.all().count()
    personas=Persona.objects.all().count()
    comisiones=Comision.objects.all().count()
    fabricaciones=Fabricacion.objects.all().count()



    context={
        "titulo":titulo,
        "compras":compras,
        "detalle_compras":detalle_compras,
        "ventas":ventas,
        "detalle_ventas":detalle_ventas,
        "materias_primas":materias_primas,
        "productos":productos,
        "personas":personas,
        "comisiones":comisiones,
        "fabricaciones":fabricaciones,


    }
    return render(request,"index.html",context)

def logout_user(request):
    logout(request)
    return redirect('inicio')
#modulos
def usuario_vista (request):
    titulo="usuarios"
    context={

        "titulo":titulo,
    }
    return render(request,"partials/usuario.html",context)
def compra_vista (request):
    titulo="compras"
    context={

        "titulo":titulo,
    }
    return render(request,"partials/compra.html",context)

def inventario_vista (request):
    titulo="Inventarios"
    context={

        "titulo":titulo,
    }
    return render(request,"partials/inventario.html",context)

def venta_vista (request):
    titulo="ventas"
    context={

        "titulo":titulo,
    }
    return render(request,"partials/venta.html",context)

def producto_vista (request):
    titulo="productos"
    context={

        "titulo":titulo,
    }
    return render(request,"partials/producto.html",context)

def accessibility (request):

    return render(request,"partials/accessibility.html")

base/templates/persona/crear.html
{% extends 'partials/body.html' %}
{% load crispy_forms_tags %}


{% block contenido %}
    <!-- Content Header (Page header) -->
    <div class="d-flex justify-content-end" style="height: 1px;">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'usuario' %}">usuarios</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'personas' %}">persona</a></li>
            <li class="breadcrumb-item active">Crear persona</li>
        </ol>
    </div>
    <!-- /.content-header -->

    <div class="wrapper">
        <div class="card">
            <h2>Crear Usuario</h2>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}

                <div class="btn-container">
                    <button class="btn btn-success" type="submit">Agregar {{ titulo }}</button>
                    <a class="btn btn-danger" href="{% url 'personas' %}">Regresar</a>
                </div>
            </form>
        </div>
    </div>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
        }

        .wrapper {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #ffffff;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .card {
            padding: 20px;
        }

        .form-control {
            margin-bottom: 15px;
        }

        .btn-container {
            display: flex;
            justify-content: center;
            margin-top: 20px;
        }

        .btn {
            margin-right: 10px;
        }
    </style>

{% endblock contenido %}

base/templates/persona/listar.html
{% extends 'partials/body.html' %}
{% load static %}

{% block contenido %}
    <!-- Content Header (Page header) -->
    <div class="d-flex justify-content-end" style="height: 1px;">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'usuario' %}">usuarios</a></li>
            <li class="breadcrumb-item active">{{ titulo }} </li>
        </ol>
    </div>
    <!-- /.content-header -->
    <div class="wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title"> {{ titulo }} </h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>


                                            <th class="notexport">°N de Registro</th>

                                            <th>Tipo de Documento</th>
                                            <th>Número de Documento</th>
                                            <th>Nombres</th>
                                            <th>Apellidos</th>
                                            <th>Teléfono</th>
                                            <th>Rol</th>
                                            <th>Correo Electrónico</th>
                                            <th class="notexport">Estado</th>
                                            <th class="notexport">Acción</th>

                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for persona in personas %}
                                            {% if persona.estado != "0" %}
                                                <tr>
                                                    <td>{{ persona.id }}</td>
                                                    <td>{{ persona.get_tipo_documento_display }}</td>
                                                    <td>{{ persona.numero_documento }}</td>
                                                    <td>{{ persona.nombres }} </td>
                                                    <td>{{ persona.apellidos }} </td>
                                                    <td>{{ persona.telefono }}</td>
                                                    <td>{{ persona.rol }}</td>
                                                    <td>{{ persona.correo_electronico }}</td>
                                                    <td>{{ persona.get_estado_display }}</td>
                                                    <td>
                                                        <button title="Eliminar Registro" type="button"
                                                                data-ids="{{ persona.id }}"
                                                                class="btnEliminar btn btn-danger bi bi-trash"
                                                                data-bs-toggle="modal" data-bs-target="#modal-danger">
                                                        </button>
                                                        <a title="Modificar Registro"
                                                           class="btn btn-primary btn-md bi bi-pencil-square"
                                                           href="{% url 'personas-modificar' persona.id %}"></a>
                                                    </td>
                                                </tr>
                                            {% endif %}
                                        {% endfor %}
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>N° de Registro</th>
                                            <th>Tipo de Documento</th>
                                            <th>Número de Documento</th>
                                            <th>Nombres</th>
                                            <th>Apellidos</th>
                                            <th>Teléfono</th>
                                            <th>Rol</th>
                                            <th>Correo Electrónico</th>
                                            <th>Estado</th>
                                            <th>Acción</th>

                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <a href="{% url 'personas-crear' %}"
                               class="boton-crear-posicion btn btn-success w-25 bi bi-person-fill-add">
                                Crear {{ titulo }}</a>
                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
        </section>
        <!-- /.content -->

    </div>

{% endblock contenido %}

base/templates/persona/modificar.html
{% extends 'partials/body.html' %}
{% load crispy_forms_tags %}


{% block contenido %}
    <!-- Content Header (Page header) -->
    <div class="d-flex justify-content-end" style="height: 1px;">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'usuario' %}">usuarios</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'personas' %}">persona</a></li>
            <li class="breadcrumb-item active">Modificar persona</li>
        </ol>
    </div>
    <!-- /.content-header -->

    <div class="wrapper">
        <div class="card">
            <h2>Modificar Usuario</h2>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}

                <div class="btn-container">
                    <button class="btn btn-success" type="submit">Modificar {{ titulo }}</button>
                    <a class="btn btn-danger" href="{% url 'personas' %}">Regresar</a>
                </div>
            </form>
        </div>
    </div>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
        }

        .wrapper {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #ffffff;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .card {
            padding: 20px;
        }

        .form-control {
            margin-bottom: 15px;
        }

        .btn-container {
            display: flex;
            justify-content: center;
            margin-top: 20px;
        }

        .btn {
            margin-right: 10px;
        }
    </style>
{% endblock contenido %}