base/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView
from accounts import views
from base.views import (
    principal,
    logout_user,
    usuario_vista,
    compra_vista,
    inventario_vista,
    venta_vista,
    producto_vista,
)

urlpatterns = [

    path('admin/', admin.site.urls),
    path("inicio/", principal, name="index"),
    path('', auth_views.LoginView.as_view(), name='inicio'),
    path('reiniciar/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reiniciar/enviar', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reiniciar/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reiniciar/completo', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('logout/', logout_user, name="logout"),

    path('usuarios/', include('usuario.urls')),
    path('compras/', include('compra.urls')),
    path('inventarios/', include('inventario.urls')),
    path('ventas/', include('venta.urls')),
    path('productos/', include('productos.urls')),
    # vistas de modulos
    path('Usuarios/', usuario_vista, name="usuario"),
    path('Compras/', compra_vista, name="compras"),
    path('Inventarios/', inventario_vista, name="inventario"),
    path('Ventas/', venta_vista, name="venta"),
    path('Productos/', producto_vista, name="producto"),
    path('inicio/abrir-pdf/', TemplateView.as_view(template_name='partials/archivo_pdf.html'), name='abrir_pdf'),

    path('templates/partials/', include('accounts.urls')),
    path('Registro Usuario', views.register, name='Registrarse'),
    path('cerrar-sesion/', views.cerrar_sesion, name='cerrar_sesion'),

]

compra/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from safedelete.models import SafeDeleteModel

from inventario.models import Materia_Prima
from usuario.models import Persona, Comision


# Create your models here.
# Modelo de Compra
class Compra(SafeDeleteModel):
    fecha = models.DateTimeField(verbose_name="Fecha de Compra", auto_now_add=True)

    # valor_total_compra = models.DecimalField(max_digits=10, decimal_places=2, default=0, validators=[MaxValueValidator(9999999999)], verbose_name="Valor total")
    class Estado(models.TextChoices):
        ACTIVO = '1', _("Activo")
        INACTIVO = '0', _("Inactivo")

    estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")

    persona_admin = models.ForeignKey(Persona, verbose_name="Administrador", on_delete=models.CASCADE,
                                      related_name="compras_administrador")
    persona_proveedor = models.ForeignKey(Persona, verbose_name="Proveedor", on_delete=models.CASCADE,
                                          related_name="compras_proveedor")

    def __str__(self):
        return "%s %s" % (self.persona_admin, self.persona_proveedor)

    class meta:
        verbose_name_plural = "Compra"


# Modelo de Detalle_Compra
class Detalle_Compra(SafeDeleteModel):
    precio_unidad = models.DecimalField(max_digits=10, decimal_places=2, validators=[MaxValueValidator(9999999999)],
                                        verbose_name="Precio Unitario")
    valor_total = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="Valor Total",
                                      editable=False)

    class Estado(models.TextChoices):
        ACTIVO = '1', _("Activo")
        INACTIVO = '0', _("Inactivo")

    estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")

    def precio_formato_colombiano(self):
        return '${:,.0f}'.format(self.precio_unidad).replace(',', '.')

    def valor_total_formato_colombiano(self):
        return '${:,.0f}'.format(self.valor_total).replace(',', '.')

    cantidad = models.PositiveIntegerField(validators=[MaxValueValidator(100)], default=0,
                                           help_text="La cantidad tiene que ser menor a 100")
    # Campo para almacenar el valor total calculado

    materia_prima = models.ForeignKey(Materia_Prima, verbose_name="Materia Prima", on_delete=models.CASCADE)
    compra = models.ForeignKey(Compra, verbose_name="Compra", on_delete=models.CASCADE)

    def __str__(self):
        return "%s" % (self.cantidad)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Detalle Compra"

compra/forms.py
from django import forms
from django.forms import ModelForm
from django_select2.forms import Select2Widget

from compra.models import Compra, Detalle_Compra, Persona, Materia_Prima


class CompraForm(ModelForm):
    # Modifica el campo persona para utilizar el widget Select2
    persona_admin = forms.ModelChoiceField(
        queryset=Persona.objects.all(),
        widget=Select2Widget,  # Utiliza el widget Select2
    )
    # Modifica el campo persona para utilizar el widget Select2
    persona_proveedor = forms.ModelChoiceField(
        queryset=Persona.objects.all(),
        widget=Select2Widget,  # Utiliza el widget Select2
    )

    class Meta:
        model = Compra
        fields = "__all__"
        exclude = ["estado"]
        success_message = 'la compra se añadió correctamente'


class CompraUpdateForm(ModelForm):
    class Meta:
        model = Compra
        fields = "__all__"
        exclude = ["id", "fecha"]
        success_message = 'la compra se actualizó correctamente'


class Detalle_CompraForm(ModelForm):
    # Modifica el campo materia_prima para utilizar el widget Select2
    materia_prima = forms.ModelChoiceField(
        queryset=Materia_Prima.objects.all(),
        widget=Select2Widget,  # Utiliza el widget Select2
    )

    class Meta:
        model = Detalle_Compra
        fields = "__all__"
        exclude = ["compra", "estado"]
        success_message = 'el detalle de la compra se añadió correctamente'


class Detalle_CompraUpdateForm(ModelForm):
    class Meta:
        model = Detalle_Compra
        fields = "__all__"
        exclude = ["id", "estado"]
        success_message = 'el detalle de la compra se actualizó correctamente'

base/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from compra.models import Compra,Detalle_Compra
from venta.models import Venta,Detalle_Venta
from inventario.models import Materia_Prima,Fabricacion
from productos.models import Producto
from usuario.models import Persona,Comision
@login_required
def principal(request):
    titulo="Bienvenido"
    compras= Compra.objects.all().count
    detalle_compras=Detalle_Compra.objects.all().count()
    ventas=Venta.objects.all().count()
    detalle_ventas=Detalle_Venta.objects.all().count()
    materias_primas=Materia_Prima.objects.all().count()
    productos=Producto.objects.all().count()
    personas=Persona.objects.all().count()
    comisiones=Comision.objects.all().count()
    fabricaciones=Fabricacion.objects.all().count()



    context={
        "titulo":titulo,
        "compras":compras,
        "detalle_compras":detalle_compras,
        "ventas":ventas,
        "detalle_ventas":detalle_ventas,
        "materias_primas":materias_primas,
        "productos":productos,
        "personas":personas,
        "comisiones":comisiones,
        "fabricaciones":fabricaciones,


    }
    return render(request,"index.html",context)

def logout_user(request):
    logout(request)
    return redirect('inicio')
#modulos
def usuario_vista (request):
    titulo="usuarios"
    context={

        "titulo":titulo,
    }
    return render(request,"partials/usuario.html",context)
def compra_vista (request):
    titulo="compras"
    context={

        "titulo":titulo,
    }
    return render(request,"partials/compra.html",context)

def inventario_vista (request):
    titulo="Inventarios"
    context={

        "titulo":titulo,
    }
    return render(request,"partials/inventario.html",context)

def venta_vista (request):
    titulo="ventas"
    context={

        "titulo":titulo,
    }
    return render(request,"partials/venta.html",context)

def producto_vista (request):
    titulo="productos"
    context={

        "titulo":titulo,
    }
    return render(request,"partials/producto.html",context)

def accessibility (request):

    return render(request,"partials/accessibility.html")

base/templates/detalle_compra/crear.html
{% extends 'partials/body.html' %}
{% load crispy_forms_tags %}

{% block contenido %}
    <div class="d-flex justify-content-end" style="height: 1px;">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'compras' %}">Compras</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'detalle_compra' %}">Detalle Compra</a></li>
            <li class="breadcrumb-item active">Crear Detalle Compra</li>
        </ol>
    </div>

    <!-- Content Header (Page header) -->

 <div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>N° Registro</th>
                <th>Fecha</th>
                <th>Admistrador</th>
                <th>Proveedor</th>
            </tr>
        </thead>
        <tbody>
            {% for compra in comprasn %}
                {% if compra.estado != "0" %}
                    <tr>
                        <td>{{ compra.id }}</td>
                        <td>{{ compra.fecha }}</td>
                        <td>{{ compra.persona_admin }}</td>
                        <td>{{ compra.persona_proveedor }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>
    <!-- Agrega el formulario de creación de compra debajo de la tabla -->
   <div class="card">
    <div class="card-header">
        <h3 class="card-title">Crear {{ titulo }}</h3>
    </div>
    <div class="card-body">
        <form action="" method="POST" id="myForm">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success" type="button" onclick="mostrarModal()">
                Agregar {{ titulo }}</button>
            <a href="{% url 'detalle_compra' %}" class="btn btn-danger">Regresar</a>
        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirmar acción</h5>
            </div>
            <div class="modal-body">
                ¿Estás seguro de que deseas agregar el detalle de compra?
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-primary" id="confirmButton">Aceptar</button>
            </div>
        </div>
    </div>
</div>
{% block extrajs %}
    {{ form.media }}
{% endblock extrajs %}
<script>
    function mostrarModal() {
        $('#confirmModal').modal('show');
    }

    $(document).ready(function() {
        $('#confirmButton').on('click', function() {
            var form = document.getElementById('myForm');
            if (form.checkValidity()) {
                form.submit(); // Envía el formulario
            } else {
                // Mostrar mensajes de error de validación en campos resaltados en rojo
                form.reportValidity();
            }
        });
    });
</script>


{% endblock contenido %}

base/templates/detalle_compra/listar.html
{% extends 'partials/body.html' %}
{% load static %}
{% block contenido %}
    <!-- Content Header (Page header) -->
    <div class="d-flex justify-content-end" style="height: 1px;">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'compras' %}">compras</a></li>
            <li class="breadcrumb-item active">{{ titulo }} </li>
        </ol>
    </div>
    <!-- /.content-header -->
    <section class="content">
        <div class="container-fluid">
            <div class="row px-1 px-sm-3" style="min-width: 270px;">
                <div class="col px-1 px-sm-3">
                    <div class="px-1 px-sm-3">
                        <div class="fs-1 fw-bold">
                            <h3 class="py-5">{{ titulo }}</h3>
                        </div>

                        <div class="d-flex">
                            <div class="p-5 mx-3 "
                                 style=" background-color: #fcf9f5; border-color: #68411d; border-width: 3px; border-style: solid;">
                                <b>Codigo de Compra</b> <br>
                                <p>{{ compra.id }}</p>
                                <b>Fecha</b> <br>
                                <p>{{ compra.fecha }}</p>
                                <b>Administrador</b><br>
                                <p>{{ compra.persona_admin }}</p>
                                <b>Proveedor</b><br>
                                <p>{{ compra.persona_proveedor }}</p>
                                {% if detalle_compras %}
                                    <!-- Verifica si hay detalles de compra en la lista -->
                                    <a type="button" href="{% url 'compra-finalizar' compra.id %}"
                                       class="btn btn-info">
                                        <i class="bi bi-trash">Finalizar Compra</i>
                                    </a>
                                {% endif %}
                                <a href="{% url 'compra' %}" class="btn btn-danger">Regresar</a>
                            </div>

                            <div class="table-responsive p-3 "
                                 style=" background-color: #fcf9f5; border-color: #68411d; border-width: 3px; border-style: solid;">
                                <table id="example1" class="table table-bordered table-striped py-5">
                                    <thead style="background-color: #fcf9f5">
                                    <tr style="background-color: #d4c6b5;text-align: center;">
                                        <th>Materia Prima</th>
                                        <th>Cantidad</th>
                                        <th>Precio Unitario</th>

                                        <th>Acciones</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for detalle_compra in detalle_compras %}
                                        {% if detalle_compra.estado != "0" %}
                                            <tr style="background-color: #f3eee9">
                                                <td style="color: #68411d;text-align: center;">{{ detalle_compra.materia_prima.nombre }}-{{ detalle_compra.materia_prima.get_tipo_display }}</td>
                                                <td style="color: #68411d; text-align: center;">
                                                    <form method="POST"
                                                          action="{% url 'aumentarr_cantidad' detalle_compra.id %}">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-sm btn-primary">+</button>
                                                    </form>
                                                    {{ detalle_compra.cantidad }}
                                                    <form method="POST"
                                                          action="{% url 'disminuirr_cantidad' detalle_compra.id %}">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-sm btn-primary">-</button>
                                                    </form>
                                                </td>
                                                <td style="color: #68411d;text-align: center;">{{ detalle_compra.precio_formato_colombiano }}</td>


                                                <td>

                                                    <form method="POST"
                                                          action="{% url 'eliminar_detalle_compra' detalle_compra.id %}">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-sm btn-danger">Eliminar
                                                        </button>

                                                    </form>
                                                </td>

                                            </tr>
                                        {% endif %}
                                    {% endfor %}
                                    <tr style="background-color: #f3eee9">
                                        <form method="POST">
                                            {% csrf_token %}
                                            <td style="color: #68411d;text-align: center;">
                                                <select name="materia_prima" class="select form-control"required=""id="id_materia_prima" style="width: 150px; height: 100px !important;" >
                                                    <option value="" selected>---------</option>
                                                        {% for materia_prima in materias %}
                                                    <option value="{{ materia_prima.id }}">{{ materia_prima }}</option>
                                                    {% endfor %}
                                                </select>
                                            </td>
                                            <td style="color: #68411d;text-align: center;">
                                                <input type="number" name="cantidad" class="numberinput form-control"
                                                       required="" id="id_cantidad" min="0" style="width: 75px;">
                                            </td>
                                            <td style="color: #68411d;text-align: center;">
                                                <input type="number" name="precio_unidad" class="numberinput form-control" required=""
                                                       id="id_precio_unidad" min="0" style="width: 150px;">
                                            </td>
                                            <td>
                                                <button type="submit" class="btn btn-success">+</button>
                                            </td>
                                        </form>
                                    </tr>

                                    </tbody>
                                </table>

                            </div>

                        </div>
                        <!-- /.card-body -->

                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <script>
        $(document).ready(function() {
            $('#id_materia_prima').select2();
        });
    </script>

{% endblock contenido %}

base/templates/detalle_compra/modificar.html
{% extends 'partials/body.html' %}
{% load crispy_forms_tags %}


{% block contenido %}
        <!-- Content Header (Page header) -->
    <div class="d-flex justify-content-end" style="height: 1px;">
            <ol class="breadcrumb float-sm-right" >
                <li class="breadcrumb-item" ><a href="{% url 'index' %}">Inicio</a></li>
                <li class="breadcrumb-item active" ><a href="{% url 'compras' %}">Compras</a></li>
                <li class="breadcrumb-item active" ><a href="{% url 'detalle_compra' %}">Detalle Compra</a></li>
                <li class="breadcrumb-item active">Modificar Detalle Compra </li>
            </ol>
    </div>
    <!-- /.content-header -->
        <form action="" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Modificar {{titulo}}">  <a href="{% url 'detalle_compra' %}" class="btn btn-danger">Regresar</a>
        </form>
{% block extrajs %}
    {{ form.media }}
{% endblock extrajs %}

{% endblock contenido %}